pipeline:
  test:
    image: ruby:2.3-alpine
    commands:
      - apk update
      - apk add build-base

      - bundle install --path=gems --retry=5 --jobs=5
      - bin/rake
  docker:
    storage_driver: overlay
    repo: plugins/drone-chef-supermarket
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Chef Supermarket
  desc: Publish files and artifacts to Chef Supermarket
  type: publish
  image: plugins/drone-chef-supermarket
  labels:
    - chef
    - ruby
