build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-chef-supermarket
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-chef-supermarket
    tag: develop
    when:
      branch: develop

plugin:
  name: Chef Supermarket
  desc: Publish files and artifacts to Chef Supermarket
  type: publish
  image: plugins/drone-chef-supermarket
  labels:
    - chef
